Algoritmo "soma"
// Descrição: Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes
// números.
// Autor(a)    : Gustavo Custódio Felipe
// Data atual  : 01/05/2024
Var

   x, y, soma : inteiro

Inicio

      escreva("Digite o valor de X: ")
      leia(x)
      escreva("Digite o valor de Y: ")
      leia(y)
      
      soma <- x + y
      
      escreva("SOMA = ",soma)

Fimalgoritmo