Algoritmo "tabuada"
// Descrição : Ler um número inteiro N, daí mostrar na tela a tabuada de N para 1 a 10.
// Autor(a)    : Gustavo Custódio Felipe
// Data atual  : 08/05/2024
Var

   n, i, resultado : inteiro

Inicio

   escreva("Deseja a tabuada para qual valor? ")
   leia(n)
   
   para i de 1 ate 10 faca
        resultado <- i * n
        escreval(n ," x ", i ," = ", resultado)
   fimpara

Fimalgoritmo