Algoritmo "teste_enquanto"
// Autor(a)    : Gustavo Custódio Felipe
// Data atual  : 05/05/2024
Var

   x, soma : inteiro

Inicio

      soma <- 0
      
      escreva("Digite o primeiro número: ")
      leia(x)
      
      enquanto x <> 0 faca
          soma <- soma + x
          escreva("Digite outro numero: ")
          leia(x)
      fimenquanto
      
      escreva("SOMA = ", soma)

Fimalgoritmo